
# Makefile for osd and tv 
obj-y +=pr_dbg.o
obj-y +=logo_display/logo_drv.o
obj-$(CONFIG_AM_TV_OUTPUT)	+= vout/
obj-$(CONFIG_AM_TCON_OUTPUT)+= vout/
obj-$(CONFIG_FB_AML_GE2D)	+= ge2d/
obj-$(CONFIG_FB_AML_APOLLO)	+= osd/
obj-$(CONFIG_FB_AML_LOGO)	+= logo_display/



