obj-y 	+=display.o
display-objs=vout_notify.o  vout_serve.o



obj-$(CONFIG_AM_TV_OUTPUT)  += am_tvout.o
am_tvout-objs :=   tvoutc.o  tvconf.o 

obj-$(CONFIG_AM_LCD_MLVDS_OUTPUT)  += mlvds.o

obj-$(CONFIG_AML_MLVDS_A_TM080XDH)  += lcd_mlvds/A_TM080XDH.o


obj-$(CONFIG_AM_LCD_LVDS_OUTPUT)  += lvds.o

obj-$(CONFIG_AML_LVDS_R_AT070TNA2)  += lcd_lvds/R_AT070TNA2.o

obj-$(CONFIG_AML_LVDS_HV070WSA_100)  += lcd_lvds/HV070WSA_100.o

obj-$(CONFIG_AM_LCD_TTL_OUTPUT)  += tcon.o

obj-$(CONFIG_AML_TTL_M3_EXAMPLE)  += lcd_ttl/M3_example.o

obj-$(CONFIG_AML_TCON_T13)  += lcd_ttl/t13.o

obj-$(CONFIG_AML_TCON_ML10)  += lcd_ttl/ml10.o

obj-$(CONFIG_AML_TCON_W10)  += lcd_ttl/w10.o

obj-$(CONFIG_AML_TCON_W7)  += lcd_ttl/w7.o

obj-$(CONFIG_AML_TCON_W7NEW)  += lcd_ttl/w7new.o

obj-$(CONFIG_AML_TCON_W8)  += lcd_ttl/w8.o

obj-$(CONFIG_AML_TCON_P7)  += lcd_ttl/p7.o

obj-$(CONFIG_AML_TCON_K7)  += lcd_ttl/k7.o

obj-$(CONFIG_AML_TCON_C7)  += lcd_ttl/c7.o

obj-$(CONFIG_AML_TCON_K8)  += lcd_ttl/k8.o

obj-$(CONFIG_AML_TCON_G7)  += lcd_ttl/g7.o

obj-$(CONFIG_AML_TCON_A18)  += lcd_ttl/a18.o

obj-$(CONFIG_AML_TCON_A19)  += lcd_ttl/a19.o

obj-$(CONFIG_AML_TCON_R10)  += lcd_ttl/r10.o

obj-$(CONFIG_AML_TCON_REFB13)  += lcd_ttl/refb13.o

obj-$(CONFIG_AML_TCON_REFB14)  += lcd_ttl/refb14.o

obj-$(CONFIG_AML_TCON_T10)  += lcd_ttl/t10.o

obj-$(CONFIG_AML_TCON_REFB17)  += lcd_ttl/refb17t13.o

obj-$(CONFIG_AML_TCON_P10)  += lcd_ttl/p10.o

obj-$(CONFIG_AML_TCON_Y7)  += lcd_ttl/y7.o

#EXTRA_CFLAGS += -DCONFIG_PM