#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SINTEK_CAPACITIVE_TOUCHSCREEN)		+= stkxxx.o
obj-$(CONFIG_ITK_CAPACITIVE_TOUCHSCREEN)		+= itk.o

