#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SINTEK_CAPACITIVE_TOUCHSCREEN)		+= stkxxx.o
obj-$(CONFIG_ITK_CAPACITIVE_TOUCHSCREEN)		+= itk.o
obj-$(CONFIG_EETI_CAPACITIVE_TOUCHSCREEN)		+= eeti.o
obj-$(CONFIG_SIS92XX_CAPACITIVE_TOUCHSCREEN) += capts.o sis92xx.o
obj-$(CONFIG_HX8520_CAPACITIVE_TOUCHSCREEN) += capts.o hx8520.o
obj-$(CONFIG_RAYDIUM_CAPACITIVE_TOUCHSCREEN) += capts.o raydium.o
obj-$(CONFIG_GOODIX_CAPACITIVE_TOUCHSCREEN) += goodix_touch.o