#
# Makefile for TVIN.
#

obj-$(CONFIG_TVIN_BT656IN) += bt656in.o
bt656in-objs := bt656_601_in.o

obj-$(CONFIG_TVIN_DVIN) += dvin.o
dvin-objs := dvin.o

obj-$(CONFIG_TVIN_VDIN) += vdin.o
dvin-objs := vdin.o tvin_format_table.o


#@todo add other device driver configuration...

