#
# Makefile for TVIN.
#

obj-$(CONFIG_TVIN_MPEGIN) += bt656in.o
bt656in-objs := bt656_601_in.o

obj-$(CONFIG_TVIN_DVIN) += dvin.o
dvin-objs := dvin.o

#@todo add other device driver configuration...

