#
# Makefile for the amlogic platform camera interface device drivers.
#

amlv4lcam-objs := gt2005.o 
amlvm-objs := common/vm.o common/plat_ctrl.o

obj-$(CONFIG_VIDEO_AMLOGIC_CAPTURE) += amlv4lcam.o
obj-$(CONFIG_AMLOGIC_VIDEOIN_MANAGER)  += amlvm.o
