#makefile for apollo ge2d

apollo_ge2d-objs=bitblt.o \
				fillrect.o \
				ge2d.o \
				ge2dgen.o\
				ge2d_wq.o\
				stretchblt.o\
				ge2d_main.o\
				blend.o
obj-$(CONFIG_FB_AML_GE2D) +=apollo_ge2d.o
EXTRA_CFLAGS += -Idrivers/amlogic/display/
									
