#
# Makefile for the amlogic i2c bus drivers.
#

#obj-$(CONFIG_AM_NAND)	+= aml_m1_nand.o
obj-$(CONFIG_NAND_FLASH_DRIVER_BASE_OPERATE)	+= aml_m1_nand_base_operate.o
obj-$(CONFIG_NAND_FLASH_DRIVER_MULTIPLANE_CE)	+= aml_m1_nand.o
