#
# Makefile for EXTERNAL DEVICE.
#


obj-$(CONFIG_CAMERA_OV2655) += camera_ov2655.o
camera_ov2655-objs := ov2655.o
#camera_ov2655-y    := ov2655.o ov2655_reg.o

obj-$(CONFIG_CAMERA_OV2665) += camera_ov2665.o
camera_ov2665-objs := ov2665.o


obj-$(CONFIG_CAMERA_OV5640) += camera_ov5640.o
camera_ov5640-objs := ov5640.o




